

baseURL = "https://drzoupeihui.github.io/"
defaultContentLanguage = "zh"
#defaultContentLanguageInSubdir = true
#disqusShortname = "guangmean"   # Optional

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

[languages]
	[languages.zh]
        languageCode = "zh-cn"
        LanguageName = "ğŸ‡¨ğŸ‡³CN"
        contentDir = "content"
        weight = 1
		[[languages.zh.menus.main]]
			name = 'é¦–é¡µ'
			pageRef = '/'
			weight = 1
		[[languages.zh.menus.main]]
			name = 'åˆ†ç±»'
			pageRef = '/categories'
			weight = 2
		[[languages.zh.menus.main]]
			name = 'ä¸“é¢˜'
			pageRef = '/categories/ä¸“é¢˜'
			weight = 3
		[[languages.zh.menus.main]]
			name = 'æ¥è¯Šæ„Ÿæ‚Ÿ'
			pageRef = '/categories/æ„Ÿæ‚Ÿ'
			weight = 30
		[[languages.zh.menus.main]]
			name = 'æ¯å‘¨ç§¯ç´¯'
			pageRef = '/categories/æ¯å‘¨ç§¯ç´¯'
			weight = 40
		[[languages.zh.menus.main]]
			name = 'è”ç³»'
			pageRef = '/contact'
			weight = 50

[params]
	copyright = "&#xA9; 2024 ~ 2025 by drzoupeihui.github.io All Rights Reserved."
	sharethis = "******"
	[params.google]
	#	google_ad_client = "******"
	#	ga4 = "******"
	[params.bannershowcase]
		categories = ["æ¯å‘¨ç§¯ç´¯"]
		limit = 2
	[params.email]
		contact = "example@gmail.com"
	[params.ignore]
	#	categories = ["privacy", "terms", "archives", "cookie"]



[outputs]
  home = ["HTML", "JSON"]   # Optional - JSON just for search